/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{html,ts}',
  ],
  theme: {
    extend: {
      fontFamily: {
        'display': ['Montserrat', 'sans-serif'],
        'display-lg': ['Montserrat', 'sans-serif'],
        'headline': ['Montserrat', 'sans-serif'],
        'headline-lg': ['Montserrat', 'sans-serif'],
        'headline-md': ['Montserrat', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1', fontWeight: '500' }],
        'label': ['14px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '40px',
      },
      borderRadius: {
        'xl': '1.5rem',
        '2xl': '1.5rem',
      },
      maxWidth: {
        'container': '1440px',
      },
      colors: {
        'surface': '#131314',
        'surface-dim': '#131314',
        'surface-bright': '#3a393a',
        'surface-container-lowest': '#0e0e0f',
        'surface-container-low': '#1c1b1c',
        'surface-container': '#201f20',
        'surface-container-high': '#2a2a2b',
        'surface-container-highest': '#353436',
        'on-surface': '#e5e2e3',
        'on-surface-variant': '#d8bfd6',
        'inverse-surface': '#e5e2e3',
        'inverse-on-surface': '#313031',
        'outline': '#a08a9f',
        'outline-variant': '#534153',
        'surface-tint': '#f7acff',
        'primary': '#f7acff',
        'on-primary': '#570067',
        'primary-container': '#e14aff',
        'on-primary-container': '#4c005b',
        'inverse-primary': '#a100be',
        'primary-fixed': '#ffd6ff',
        'primary-fixed-dim': '#f7acff',
        'on-primary-fixed': '#350040',
        'on-primary-fixed-variant': '#7b0091',
        'secondary': '#d3fbff',
        'on-secondary': '#00363a',
        'secondary-container': '#00eefc',
        'on-secondary-container': '#00686f',
        'secondary-fixed': '#7df4ff',
        'secondary-fixed-dim': '#00dbe9',
        'on-secondary-fixed': '#002022',
        'on-secondary-fixed-variant': '#004f54',
        'tertiary': '#2ae500',
        'on-tertiary': '#053900',
        'tertiary-container': '#1da800',
        'on-tertiary-container': '#043200',
        'tertiary-fixed': '#79ff5b',
        'tertiary-fixed-dim': '#2ae500',
        'on-tertiary-fixed': '#022100',
        'on-tertiary-fixed-variant': '#095300',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'background': '#131314',
        'on-background': '#e5e2e3',
        'surface-variant': '#353436',
      },
    },
  },
  plugins: [],
};
